version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - investment-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  investment-network:
    driver: bridge 